### ISSUE TITLE
Permission denied or other errors... (Run on Startup.d)

### ISSUE THREAD

**Issue by pickonedev** [adamoutler/HassOSConfigurator#17]
Hi! @adamoutler 

Any idea how to pass this error? I try to mount a drive to a folder on samba, ssh and frigate addons, but no luck, only errors...

```
executing
#############################################################################
###############/config/startup/startup.d/addon_ccab4aaf_frigate.sh
###############Container: 6ad55af52dcb: tmp/addon_ccab4aaf_frigate.startup.sh
#############################################################################
chmod: cannot access '/tmp/addon_ccab4aaf_frigate.startup.sh': No such file or directory

exec: fatal: unable to exec /tmp/addon_ccab4aaf_frigate.startup.sh: No such file or directory

#############################################################################
###############/config/startup/startup.d/addon_a0d7b954_ssh.sh
###############Container: 5297df21dff7: tmp/addon_a0d7b954_ssh.startup.sh
#############################################################################
mount: permission denied (are you root?)

#############################################################################
###############/config/startup/startup.d/addon_core_samba.sh
###############Container: 471306e8e4c9: tmp/addon_core_samba.startup.sh
#############################################################################
mount: mounting /dev/sda1 on /media/hp-drive failed: Permission denied

```

Thank you in advance!

**Comment by adamoutler** [comment]
Disable protection mode.

**Comment by pickonedev** [comment]
It was already disabled, but not working... Any other idea?

![image](https://user-images.githubusercontent.com/34201387/168030567-ba0a0314-1a56-4868-be3e-5ea71158acbe.png)

**Comment by pickonedev** [comment]
Do you know any other solution, please?

Edit: By the way... with "run on startup.d" addon installed, I couldn't update home assistant core. Everytime I wanted to update HA core, I couldn't load the interface anymore. After I force reboot the computer, HA starts but with the same core version, without update. Trying to update it through SSH, I've seen that there was an error similar to "Docker container already exists"... and so on... I uninstalled your addon and the update has been done without problems.

Maybe this have something to do with the initial problem of mine? Any idea?

**Comment by adamoutler** [comment]
My wife and kid gave me time for Father's day.   Issues are fixed.

**Comment by pickonedev** [comment]
Happy Father's day.

For me, I still get the permission error, but maybe I don't have the latest modified version?! How can I update it? 

Run On Startup.d
Current version: 0.11



```
#############################################################################
###############/config/startup/startup.d/addon_core_samba.sh
###############Container: 11917b0af5b4: tmp/addon_core_samba.startup.sh
#############################################################################
mount: mounting /dev/sda1 on /media/hp-drive failed: Permission denied


----DONE----  sleeping...
```

**Comment by adamoutler** [comment]
Nothing I can do about that.  The script is executing in the context of the docker container.  Maybe try sudo or a different container.
