### ISSUE TITLE
Repository is not showing add ons on new Hasio instalation

### ISSUE THREAD

**Issue by elucas2uy** [adamoutler/HassOSConfigurator#25]
hi, I had 2 new installs of HasIO yesterday and decide to add the usual repositories but this one is not showing add ons.

Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

First I added the repository:
![image](https://user-images.githubusercontent.com/28520368/191531647-42fc8c32-7762-48c4-9f34-9cddb906adca.png)

Then no add ons showed in the store:

![image](https://user-images.githubusercontent.com/28520368/191531998-b8776ceb-bbed-48c6-8bec-54e5328b2783.png)

I have tried rebooting and it does not work.
The HasIO logs are not showing errors at all. 

I do not know any other debug procedure to follow.

NOTE: I have the I2C working anyway by doing it the long way, but I whant to advice of this problem in case if it is not only me.

Regards.

**Comment by adamoutler** [comment]
I'm not really sure.  They should show up unless the architecture is unsupported or there was an error with synchronizing the repositories.   Try this one which is a collection of all of my Addons. https://github.com/adamoutler/Addons

**Comment by elucas2uy** [comment]
Hi, the one above (https://github.com/adamoutler/Addons) show some add on but not all of them (I think)....
![SmartSelect_20220921_180514_Chrome](https://user-images.githubusercontent.com/28520368/191610225-70ed92d5-b7ff-4854-865b-8eb84878efbe.jpg)


By the way, your Armor One addon is working perfect (https://github.com/adamoutler/HassOSArgonOneAddon).

But after all, the i2c Add on do not want to work 🙄 🙃

**Comment by bengtner** [comment]
I made the same experience, but after a refresh of the page the addon showed up.

**Comment by dtwilliamson** [comment]
Refreshing the Addon Store page worked for me, too.

**Comment by adamoutler** [comment]
Is this fixed now?

**Comment by dtwilliamson** [comment]
I used the https://github.com/adamoutler/HassOSConfigurator (not the https://github.com/adamoutler/Addons) repository. The addons didn't appear in the store. Once I did a browser refresh they did.

**Comment by elucas2uy** [comment]
HI, it still not working for my on Raspberry pi 4.

Is not a difficult procedure, so I really do not know where the problem could be.

**Comment by elucas2uy** [comment]
> I used the https://github.com/adamoutler/HassOSConfigurator (not the https://github.com/adamoutler/Addons) repository. The addons didn't appear in the store. Once I did a browser refresh they did.

It still not working for me after reload the page in the browser.... I did not try other browsers but Chrome... may be a browser problem?

**Comment by dtwilliamson** [comment]
I'm using Chrome 104.0.5112.79

**Comment by adamoutler** [comment]
Certain add-ons only work for certain architectures.

**Comment by tgryphon** [comment]
HA required me to enable Advanced Mode to find and use the repository.

**Comment by adamoutler** [comment]
Hrm.  Ok.  I have never operated in basic mode or whatever so I didn't know that.  It would be preferred to have this be advanced though so it will stay.

**Comment by adamoutler** [comment]
Docs need update

**Comment by Csepi** [comment]
Dear @adamoutler , docs still need an update, nowhere in the installation guide I didn't find a piece of relevant information about this. I was about to open a ticket when I found this closed one, and Advanced mode helped!

Thanks in advance anyway for the addon!!!!
