### ISSUE TITLE
SSH Configurator not working on hassos odroid-n2+

### ISSUE THREAD

**Issue by anduchs** [adamoutler/HassOSConfigurator#8]
Hi, I'm running Hassos on a bpi-n2+ and it seems that there is a different name for the emmc here.

Here's my output:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
no sda1 config found
no sdb1 config found
no mmcblk0p1 config found
no nvme0n1p1 config found
This Configurator did it's job. Perform a hard-power-off now. This configurator only works once and is no longer needed.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Any idea ?
P.S. Getting authorized keys onto the device using the CONFIG usb stick also did not work... :-(

**Comment by adamoutler** [comment]
I'll need a `ls /dev` from terminal app

**Comment by anduchs** [comment]
```
$ ls /dev | tr '\n' ' '
autofs block bsg bus cec0 char console cpu_dma_latency cuse disk dri fb0 fd full fuse gpiochip0 gpiochip1 hugepages hwrng i2c-0 i2c-1 i2c-2 iio:device0 input kmsg kvm log loop-control loop0 loop1 loop2 loop3 loop4 loop5 loop6 loop7 mapper mem mmcblk1 mmcblk1boot0 mmcblk1boot1 mmcblk1p1 mmcblk1p2 mmcblk1p3 mmcblk1p4 mmcblk1p5 mmcblk1p6 mmcblk1p7 mmcblk1p8 mmcblk1p9 mmcblk1rpmb mqueue net null port ptmx pts ptyp0 ptyp1 ptyp2 ptyp3 ptyp4 ptyp5 ptyp6 ptyp7 ptyp8 ptyp9 ptypa ptypb ptypc ptypd ptype ptypf random rfkill rtc rtc0 rtc1 sda sda1 serial shm snapshot snd stderr stdin stdout tty tty0 tty1 tty10 tty11 tty12 tty13 tty14 tty15 tty16 tty17 tty18 tty19 tty2 tty20 tty21 tty22 tty23 tty24 tty25 tty26 tty27 tty28 tty29 tty3 tty30 tty31 tty32 tty33 tty34 tty35 tty36 tty37 tty38 tty39 tty4 tty40 tty41 tty42 tty43 tty44 tty45 tty46 tty47 tty48 tty49 tty5 tty50 tty51 tty52 tty53 tty54 tty55 tty56 tty57 tty58 tty59 tty6 tty60 tty61 tty62 tty63 tty7 tty8 tty9 ttyACM0 ttyAML0 ttyAML1 ttyS0 ttyS1 ttyS2 ttyS3 ttyp0 ttyp1 ttyp2 ttyp3 ttyp4 ttyp5 ttyp6 ttyp7 ttyp8 ttyp9 ttypa ttypb ttypc ttypd ttype ttypf urandom vcs vcs1 vcs2 vcs3 vcs4 vcs5 vcs6 vcsa vcsa1 vcsa2 vcsa3 vcsa4 vcsa5 vcsa6 vcsu vcsu1 vcsu2 vcsu3 vcsu4 vcsu5 vcsu6 vfio vga_arbiter zero zram0 zram1 zram2
```

I appreciate the help !

**Comment by anduchs** [comment]
P.S. I assume, sha1 is my usb stick, thus not the early-fail...

**Comment by anduchs** [comment]
Anything I can do to help ?
I assume that I would just need to add mmcblk1 to the list, but I'm not sure.
Also I cannot really access the addon on disk, since I don't have SSH which is why I wanted it.
If you could confirm the exact thing, I can also post a PR here.

**Comment by adamoutler** [comment]
Updated but I did not increment version.   Uninstall, update market, then reinstall to test.

**Comment by anduchs** [comment]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
no vda1 config found
no sda1 config found
no sdb1 config found
no mmcblk0p1 config found
no mmcblk1p1 config found
no nvme0n1p1 config found
This Configurator did it's job. Perform a hard-power-off now. This configurator only works once and is no longer needed.
```
:-(

**Comment by adamoutler** [comment]
Can you try the steps in #10 ?

**Comment by anduchs** [comment]
![Unbenannt](https://user-images.githubusercontent.com/4572892/135811653-1ad02008-bac7-4c35-8fd4-3c526ddb1eec.PNG)

I did disable the protected mode, but as you can see to no avail...

P.S. sudo also does not change anything

**Comment by adamoutler** [comment]
Looks like terminal app can no longer mount. I just tried it on my machine.  Sorry.  Regardless, this was fixed in the latest revision where we now support mmcblk1p1.

**Comment by anduchs** [comment]
I just ran v0.9 but still not working:
```
no vda1 config found
no sda1 config found
no sdb1 config found
no mmcblk0p1 config found
no mmcblk1p1 config found
no nvme0n1p1 config found
This Configurator did it's job. Perform a hard-power-off now. This configurator only works once and is no longer needed.
```

P.S. Secure mode is off for the addon

**Comment by adamoutler** [comment]
Let's check your output of `ls -al /dev`

**Comment by anduchs** [comment]
I assume this is the part you need:
```
crw-r-----    1 root     kmem        1,   1 Oct  4 15:17 mem
brw-rw----    1 root     disk      179,   0 Oct  4 15:17 mmcblk1
brw-rw----    1 root     disk      179,  32 Oct  4 15:17 mmcblk1boot0
brw-rw----    1 root     disk      179,  64 Oct  4 15:17 mmcblk1boot1
brw-rw----    1 root     disk      179,   1 Oct  4 15:17 mmcblk1p1
brw-rw----    1 root     disk      179,   2 Oct  4 15:17 mmcblk1p2
brw-rw----    1 root     disk      179,   3 Oct  4 15:17 mmcblk1p3
brw-rw----    1 root     disk      179,   4 Oct  4 15:17 mmcblk1p4
brw-rw----    1 root     disk      179,   5 Oct  4 15:17 mmcblk1p5
brw-rw----    1 root     disk      179,   6 Oct  4 15:17 mmcblk1p6
brw-rw----    1 root     disk      179,   7 Oct  4 15:17 mmcblk1p7
brw-rw----    1 root     disk      179,   8 Oct  4 15:17 mmcblk1p8
brw-rw----    1 root     disk      179,   9 Oct  4 15:18 mmcblk1p9
crw-------    1 root     root      240,   0 Oct  4 15:17 mmcblk1rpmb
```

**Comment by adamoutler** [comment]
Hrm.  This has an RPMB.  that means it's an eMMC.   The layout may be substantially different.   I think we must try something else.   

For each of those items.. eg mmcblk1boot0, mmcblk1boot1, mmcblk1p1... can you try to do this from the HASS terminal with a keyboard/mouse connected?   

`mkdir /tmp/mmcblk1boot0`
Then
`mount /dev/mmcblk1boot0 /tmp/mmcblk1boot0/`

Finish it with
`ls -ald /tmp/mmc* >/tmp/txt.txt`
`ls /mnt/boot >/tmp/txt.txt`
`mount| grep mmcblk >/tmp/txt.txt`

Then 
`docker cp /tmp/txt.txt homeassistant:/config/txt.txt`

The resulting file will be txt.txt in your home assistant config. Please pastebin the contents.  You can use pastebin.adamoutler.com and copy the url here. 

I don't know if we're going to be able to do anything here. It's possible they have protected the boot partition and removed your permissions to modify it after boot.  This is a security feature of eMMC.  If this is the case and we cannot mount anything, then I don't know what to do.

**Comment by anduchs** [comment]
You mean without a screen (blindly) ?
Does homeassistant boot to a bash directly ?

**Comment by GledholtHall** [comment]
Same problem

**Comment by W00D00** [comment]
Hi,

is there any news regarding this topic? I want to use the I2C bus on ODROID-N2+.
Thanks,

**Comment by adamoutler** [comment]
This is for SSH.

**Comment by anduchs** [comment]
I ended up removing the mmc and pluging it into my laptop via usb-adapter and changing stuff directly.
Apparently the whole `copy configs from boot-partition` scheme is broken with the HassOS image.
